version: '3.4'

services:
  testdocker:
    image: testdocker
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /mnt/data/rec_data:/data:rw
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py "]
    ports:
      - 5678:5678
